// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pgwjhkstyrumsechhayo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBnd2poa3N0eXJ1bXNlY2hoYXlvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2NjA1ODQsImV4cCI6MjA2NjIzNjU4NH0.6gJRQ8g8W6plEbNsGLlBaWMFEv9VrPdCEk39TD3Ynts";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);